#!/usr/local/bin/node

/*!
 * ================================================================
 * 
 * jsdoc2jsduck
 * https://github.com/fluidblue/jsdoc2jsduck
 * 
 * Created by Max Geissler
 * http://maxgeissler.com
 * 
 * You should have received a copy of the license along with this
 * program; if not, see <https://github.com/fluidblue/jsdoc2jsduck>
 * 
 * ================================================================
 */

var fs = require('fs');
var path = require('path');
var optimist = require('optimist');

outDir = "./out";

function process(file)
{
	rawData = fs.readFileSync(file, 'utf8');
	data = JSON.parse(rawData);

	for (var i = 0; i < data.length; i++)
	{
		console.log(data);
	}
}

function saveFile(file, data)
{
	fs.writeFile(file, data, function (err)
	{
		if (err)
		{
			console.log('Error: Cannot save output file ' + file);
			process.exit(1);
		}

		console.log('Finished.');
	});
}

function getArgv()
{
	return optimist.usage('jsdoc2jsduck.\nUsage: $0')
		.demand('i')
		.alias('i', 'in')
		.describe('i', 'Input JSON file generated by JSDoc')

		.alias('o', 'out')
		.describe('o', 'Output directory')
		.default('o', './out')

		.argv;
}

function main()
{
	var argv = getArgv();

	var inFile = argv.in;

	if (argv.out !== '')
		outDir = argv.out;

	console.log('Input file: ' + inFile + '\nOutput dir: ' + outDir);

	process(inFile);
}

main();
